### ISSUE TITLE
Can't disable air purifier option

### ISSUE THREAD

**Issue by 7RDR7** [haywirecoder/homebridge-frigidaire-dehumidifier#2]
Hi, thanks for creating this plugin. I also use your Envisalink plugin, which is great! When I installed the Frigidaire plugin and filled in the configuration screen, I selected to disable the air purifier option, but it creates an air purifier device anyway. I also can't delete the air purifier device. My humidifier does not have the air purifier option. I tried deleting everything and starting over, but the result was the same. I'm using "homebridge-frigidaire-dehumidifier v1.0.3". The Homebridge config is correct, please see below. Thoughts?

 "deviceRefresh": 90,
            "dehumidifierMode": 5,
            "enableAirPurifier": false,
            "sessionKeyRefresh": 9,
            "platform": "FrigidaireAppliance"

**Comment by haywirecoder** [comment]
Hi,

Found the issue and publish the new package. Your configuration shouldn't have to change and the Air purifier should disappear from HomeKit.

**Comment by 7RDR7** [comment]
That did it! Thanks!
