### ISSUE TITLE
Home slide bar does not match the dehumidifier setting

### ISSUE THREAD

**Issue by 7RDR7** [haywirecoder/homebridge-frigidaire-dehumidifier#3]
The slide bar does not match the dehumidifier setting. This could be design intent.
Slide bar -  Dehumidifier
100 - 85
90 - 80
80 - 75
70 - 70
60- 65
50 - 60
40 - 55
30 - 50
20 - 45
10 - 40
0 - 35

**Comment by haywirecoder** [comment]
Hi,

This is by design. Based on the Frigidaire mobile app the dehumidifier has an upper limit (100%) of 85% and lower limit (0%) of 35%.

**Comment by 7RDR7** [comment]
Thanks for the info. Closing this issue.
