### ISSUE TITLE
Login Error: undefined Unauthorized

### ISSUE THREAD

**Issue by jkristinsson** [haywirecoder/homebridge-frigidaire-dehumidifier#5]
homebridge-frigidaire-dehumidifier v1.0.7 on HomeBridge 1.6.1 with Node.js 18.16.0
Configured the Frigidaire plugin with email as username (since that is what is used to log in on both the Frigidaire.com webpage and the Frigidaire 2.0 iOS app. Verified username/password by logging in/out on both those services.

However, when starting up HomeBridge, I get an undefined error:
`[03/06/2023, 13:31:13] [FrigidaireAppliance] Frigidaire Login Error:  undefined Unauthorized`

Appliance: GALLERY FGAC7044U1 DEHUMIDIFIER

Could this be related to https://github.com/bm1549/home-assistant-frigidaire/issues/33 ?

**Comment by haywirecoder** [comment]
Unfortunately it same issue as everyone else in the community. Something has changed on the server side.

**Comment by haywirecoder** [comment]
Posted a fix if you want to be an early tester. The update does require an additional package (unrelated to this fix but is going to be part of the update to address a GitHub policy issue).  Testing ...will release in a week or so after seeing anything else break.

Add the following package via the Homebridge terminal
sudo npm install crypto-js

-- Replace 
frigidairmain.js
constants.json (add)

**Comment by haywirecoder** [comment]
Correct in version 1.0.9
