### ISSUE TITLE
Login error: undefined Forbidden

### ISSUE THREAD

**Issue by anwnn** [haywirecoder/homebridge-frigidaire-dehumidifier#6]
As of a couple days ago, it looks like login to the Frigidaire servers is failing. Logs show repeated attempts failing: 

```
[1/24/2024, 8:05:30 AM] [Dehumidifier] Frigidaire Login Error:  undefined Forbidden
[1/24/2024, 8:07:00 AM] [Dehumidifier] Frigidaire Get Error:  undefined Forbidden EndPoint: /config-files/haclmap/latest_version
[1/24/2024, 8:07:00 AM] [Dehumidifier] Background refreshing detected sessions is no longer valid, attempting to re-login.
```

**Comment by haywirecoder** [comment]
It looks like Frigidaire changed the login API endpoint. Monitoring some newsgroup and will update plug-in once determine new login endpoint. Assuming Frigidaire hasn't completely lock this down now.

**Comment by haywirecoder** [comment]
The API recently changed drastically and requires a sufficient amount of work. An update will come in a few weeks.

**Comment by haywirecoder** [comment]
A new version has been posted with support for the new API.  If you'd like to try an early version, you can clone the repo, but please keep in mind that it is still being tested, assuming everything is working as expected. A new version will be released before month end.

**Comment by haywirecoder** [comment]
2.0.0 addresses this issue.

**Comment by anwnn** [comment]
Was finally able to get around to testing the update. Works great. Thank you!
